feat: docker compose and ormconfig.js
lukemorales/gobarber-2020 pull request #12
Opened 2020-12-22 01:19 UTC by H4ad

E aí meu rei,

Esse PR foi criado para ter um setup mais fácil de configuração do banco de dados para o server, 
além de incluir também umas configurações mais complexas no `ormconfig.js`.

As mudanças foram:
- Adicionado um `docker-compose.yml`.
- Adicionado `envalid` para validar as variáveis de ambiente.
- Adicionado mais configurações para o `ormconfig.js` baseado nas variáveis de ambiente customizadas com o `.env`.

2021-01-21 23:05 UTC, lukemorales requested changes
Nice work @H4a, thanks for the contribuition and for the awesome work!
I just made a few requests, could you handle them?

2021-01-21 23:05 UTC, lukemorales commented on server/README.md
> +e depois copie o conteúdo do arquivo `env.example` para dentro do `.env`.
Those instructions are very well documented, but I think we can simplify this telling the user to do a bash command like
```bash
cp .env.example .env
```

2021-01-21 23:05 UTC, lukemorales commented on server/docker-compose.yml
> +    image: postgres:12.4
I'm using the kartoza/postgis image, it can have some differences from the postgres image, such as generating the UUIDs and some things that can show up throughout the development process. I think it's safer if we standardize to the same image I started developing

2021-01-21 23:05 UTC, lukemorales commented on server/README-pt-BR.md
> +e depois copie o conteúdo do arquivo `env-pr-BR.example` para dentro do `.env`.
Let's keep only the .env.example file, there's no need to have the translated version on a setup file. That was a great move, but since all of your code is already in English, it doesn't really suit our patterns.

2021-01-21 23:05 UTC, lukemorales commented on server/README.md
> +There are a few steps to be able to configure the database in this API, first make sure you have installed it:
Just adjusting a little bit the sentence:
`There are a few steps to be able to setupthe database for this API, first, make sure you have installed:`

2021-01-21 23:05 UTC, lukemorales commented on server/README-pt-BR.md
> +Primeiro, crie um arquivo chamado `.env`, ele irá configurar algumas coisas do banco de dados e da API,
Line 7 already is the first step, so to make that more aligned with the steps the user is following remove the "Primeiro" for something like "Em seguida"

2021-01-21 23:05 UTC, lukemorales commented on server/README.md
> +First, create a file called `.env`, it will configure some things in the database and the API,
Same as the portuguese version, line 7 is already the first step. Replace "First," for something like "Then,"

2021-01-21 23:05 UTC, lukemorales commented on server/README.md
> +First, create a file called `.env`, it will configure some things in the database and the API,
Also adjusting a little bit of the sentence:
```Then create a file called `.env`, it will store some settings for the database and the API,```

2021-01-21 23:05 UTC, lukemorales commented on server/README.md
> +After that, your Postgres database will be working, and you can
Ajusting the sentence:
`Now your Postgres database will be working and you can start..."

2021-01-21 23:05 UTC, lukemorales commented on server/README.md
> +There are some basic commands in `package.json` that help you to manage the database, they are:
Adjusting the sentence:
```There are some basic commands in `package.json` that will help you manage the database, they are:```

2021-01-21 23:05 UTC, lukemorales commented on server/env-pt-BR.example
> +##############################################################
Thanks for the work while translating and making this file, but let's just keep the .env one.

2021-01-22 00:26 UTC, H4ad commented on server/README.md
> +e depois copie o conteúdo do arquivo `env.example` para dentro do `.env`.
I had not put the command with the cp` `because it would be tying the instructions to MacOS and Linux but will follow this way.

2021-01-22 00:33 UTC, H4ad commented on server/docker-compose.yml
> +    image: postgres:12.4
This image was the default postgres image and also supports UUIDs, but I will change it to `kartoza / postgis`.

2021-01-22 00:34 UTC, H4ad commented on server/README-pt-BR.md
> +e depois copie o conteúdo do arquivo `env-pr-BR.example` para dentro do `.env`.
Ok!

2021-01-22 00:35 UTC, H4ad commented on server/README.md
> +There are a few steps to be able to configure the database in this API, first make sure you have installed it:
Fixed!

2021-01-22 00:36 UTC, H4ad commented on server/README-pt-BR.md
> +Primeiro, crie um arquivo chamado `.env`, ele irá configurar algumas coisas do banco de dados e da API,
Fixed!

2021-01-22 00:37 UTC, H4ad commented on server/README.md
> +First, create a file called `.env`, it will configure some things in the database and the API,
Fixed!

2021-01-22 00:37 UTC, H4ad commented on server/README.md
> +After that, your Postgres database will be working, and you can
Ok, fixed!

2021-01-22 00:38 UTC, H4ad commented on server/README.md
> +There are some basic commands in `package.json` that help you to manage the database, they are:
Fixed!

2021-01-22 00:39 UTC, H4ad commented on server/env-pt-BR.example
> +##############################################################
Ok, I thought it would be better to have some descriptions of the env variables in Portuguese as in the English version, but I will remove this file.

2021-01-22 01:09 UTC, lukemorales approved these changes
You're the man @H4ad

2021-01-22 01:09 UTC, merged